"use strict"

export enum ESwitchType {
  SINGLE_POLE_SINGLE_THROW = "SINGLE_POLE_SINGLE_THROW",
  SINGLE_POLE_DOUBLE_THROW = "SINGLE_POLE_DOUBLE_THROW",
  DOUBLE_POLE_SINGLE_THROW = "DOUBLE_POLE_SINGLE_THROW",
  DOUBLE_POLE_DOUBLE_THROW = "DOUBLE_POLE_DOUBLE_THROW",
  SPST = "SINGLE_POLE_SINGLE_THROW",
  SPDT = "SINGLE_POLE_DOUBLE_THROW",
  DPST = "DOUBLE_POLE_SINGLE_THROW",
  DPDT = "DOUBLE_POLE_DOUBLE_THROW",
  "4PDT" = "FOUR_POLE_DOUBLE_THROW"
}